moodlehq/moodle-local_moodlecheck

locallib.php
At the moment, this system does exclude .git repo's by default, but does not exclude .hg repo's by default. This fixes that.
=> Added support for hg repositories

version.php
Setting a component will be required once [MDL-48494](https://tracker.moodle.org/browse/MDL-48494) is done.
=> Add component

rules/phpdocs_basic.php
And discard null one as far as it cannot match function type
declaration ever. Before the patch, when there was a function type
declaration, the whole php  type was being used.
Originally reported @ https://tracker.moodle.org/browse/MDLSITE-5230
To verify it works, just add to the phpdoc of any function having typed params a "piped" `null` to its param phpdoc.. and verify it works. If you add anything different, it will fail because then the phpdoc type won't match the function one.
=> MDLSITE-5230 phpdocs: support pipe (|) multiple types

lang/en/local_moodlecheck.php, rules/phpdocs_basic.php, tests/fixtures/classtags.php, tests/moodlecheck_rules_test.php
This made sense in the past where we typically had many classes in one
library file and it was useful to keep track of who holds copyright and
credit for each of the added class.
But today, with autoloading being the common and recommended practise,
we only have one class per file. So the information about the copyright
and license is typically duplicated - once in the file's phpdoc block
and then the same info in the class' block.
=> MDL-60786 Stop requiring @copyright and @license for individual classes

file.php
To be able use local_moodlecheck on Windows development environments too, it is cucial, that filepaths are normalized, so it won't echo warnings or errors due to mismatch of '\' and '/' as directory separators.
=> normalize file paths to make checks for package system independent

index.php, lang/en/local_moodlecheck.php, renderer.php, styles.css
When running the tool over large plugins/areas of code, it would be helpful to see immediately the pass/fail summary (like codechecker does) instead of having to manually inspect the results
=> Show success/error summary after report.

.travis.yml, file.php, lang/en/local_moodlecheck.php, rules/phpdocs_basic.php, tests/fixtures/phpdoc_tags_inline.php, tests/moodlecheck_rules_test.php
Add some new checks and tests to ensure that the handling
of inline tags (@link and @see) is correct and following the
agreement @ https://tracker.moodle.org/browse/MDLSITE-6105
- Both can be used standalone and inline
- @link always must be followed by url
- both @link and @see must be followed by only 1 word (url or fdqn)
Also, update travis to current supported php and moodle branches.
=> CONTRIB-8095 local_moodlecheck: Update inline tags handling

file.php, tests/fixtures/anonymous/anonymous.php, tests/fixtures/anonymous/assigned.php, tests/fixtures/anonymous/extends.php, tests/fixtures/anonymous/extendsandimplements.php, tests/fixtures/anonymous/implements.php, tests/fixtures/anonymous/named.php, tests/moodlecheck_rules_test.php
Do not require docblocks for anonymous classes.
Anonymous classes were introduced in PHP 7.0, and are used by Moodle's code coverage configuration.
Fixes #50
Note: This original patch was by @ewallah in #51, but I have made the following changes:
- remove unnecessary Travis configuration
- remove merge commit
- add unit tests
- meet coding style
- add additional cases (no extension, and implementing interfaces)
=> Anonymous class phpdoc

rules/coreapis.txt, rules/phpdocs_package.php, tests/moodlecheck_rules_test.php
It raised my attention to see that I got an error
https://integration.moodle.org/job/Precheck%20remote%20branch/92421/artifact/work/smurf.html#phpdoc
"Category admin is not valid"
even when the "admin" should be considered valid core API. I realized the reason was that the heading in the docs was
```
=== Admin settings (admin) ===
```
and because there was no "API" mentioned in it, the "admin" was not parsed as a valid category value.
I was able to fix this easily by changing the section title in the docs (and one another, too) -  https://docs.moodle.org/dev/index.php?title=Core_APIs&type=revision&diff=57824&oldid=57817
However, I thought it would be nice to have the check covered by a unit test so I added one.
Also fix the docs page URL and make the regexp search a bit more robust
just …
=> Add unit test for fetching the list of @category values

file.php, rules/phpdocs_basic.php
I got this error in codechecker:
```
Inline phpdocs tag {@see \auth_oauth2\auth::complete_login()} with incorrect contents found. It must match {@link valid URL} or {@see valid FQSEN}
```
There is nothing wrong here but apparently moodlecheck treats digits as word separators
=> Digits can be used in classes and functions names

.travis.yml, tests/fixtures/phpdoc_tags_inline.php, tests/moodlecheck_rules_test.php
Also
- Remove php70 tests because they don't support return :void
- Remove old versions using PHPUnit 6.x because they are missing the
stringContainsString() assertion.
- Reorganize the travis files to avoid using exceptions and change
to explicit positive alternative.
=> Update tests to phpunit 8.5

.github/workflows/ci.yml, .travis.yml, file.php, rules/phpdocs_basic.php
Also, add the ability to travis runs to log-in to
DockerHub to avoid pulling rate limits.
With this patch, if both DOCKER_USER and DOCKER_TOKEN are defined
as environmental variables, they will be used to perform a login
to dockerhub, getting rid of pull limits.
Exactly the same than https://github.com/moodlehq/moodle-local_codechecker/pull/133
but applied to this repo.
=> Add Github Actions to local_moodlecheck

file.php, rules/phpdocs_basic.php, tests/fixtures/phpdoc_file_required_no1.php, tests/fixtures/phpdoc_file_required_no2.php, tests/fixtures/phpdoc_file_required_no3.php, tests/fixtures/phpdoc_file_required_yes1.php, tests/fixtures/phpdoc_file_required_yes2.php, tests/fixtures/phpdoc_file_required_yes3.php, tests/moodlecheck_rules_test.php
Now we detect all the classes, interfaces and traits in a file
and, if there is only one, then we stop requiring the file
phpdoc block.
This was agreed @ https://tracker.moodle.org/browse/MDLSITE-2804
and https://github.com/moodlehq/moodle-local_moodlecheck/issues/66
was created to implement it.
Note this doesn't address the whole agreement, but just the
detail about stop requiring the file phpdoc block, because it
is specially annoying and recurring in new files (that use to
be 1-artifact ones).
=> Stop requiring the file phpdoc block for 1-artifact files

tests/moodlecheck_rules_test.php
The assertEqualXMLStructure() assertion has been deprecated in
PHPUnit 9 and will be removed in PHPUnit 10.
As far as we were using it only to count elements, it has
been replaced by a simple XPath search.
Source: https://github.com/sebastianbergmann/phpunit/blob/9.1.0/ChangeLog-9.1.md
=> Replace assertEqualXMLStructure() by similar checks

file.php, tests/fixtures/phpdoc_tags_general.php, tests/moodlecheck_rules_test.php
This patch adds support for variadic function (aka splat) and expands test.
Suggested phpdoc annotation to support:
`@param <type> ...$args`
this is in line with known tools ([more info](https://github.com/20Tauri/DoxyDoxygen/issues/135#issuecomment-512090231)).
Fixes #42
=> Add support for variadic function and add more tests.

classes/privacy/provider.php, file.php
This tool has limited namespace handling capabilities and
we always have been getting, exclusively, the last part of
every namespace detected in function params.
This was the default behavior for PHP7 tokenizer and, in fact,
when reading the phpdocs for those params... we are removing
everything but the final part of the namespace too.
But PHP8 changed the default behavior and its tokenizer now
returns the complete namespace as unique token.
https://wiki.php.net/rfc/namespaced_names_as_token
So, to keep everything working as it was... when we detect that
some type of the function params contains namespaces, we are also
going to remove everything but the final part of the namespace.
That matches previous behaviour 100%.
If some day we want to go processing full namespaces (instead of
their …
=> Ensure that only the final part of namespaces is returned

.github/workflows/ci.yml, .travis.yml, version.php
Note that this is build on top of #73 and only can be merged after it!
Only real required change  is to set the new
max_input_vars=5000 requirement. Strictly speaking
only needed for php8, but it doesn't hurt with
older php versions and older moodle branches, so
setting it up always.
About the xmlrpc-beta extension, it's only needed
for php8 runs and only if the plugin uses xmlrpc
for something. Else, it can be omitted without
problem, as far as it's not a moodle requirement
but only a recommendation.
Finally, also bump version.php to current date
and make Moodle 3.5 (2018051700) required. This is
to make a new release in the plugins database.
=> Perform some php8 runs with 311 and master

.github/workflows/ci.yml
New mariadb:10.6 makes the COMPRESSED row format read-only by default
because it's deprecated now and will be removed in mariadb:10.7
This is being tracked @ https://tracker.moodle.org/browse/MDL-72131
Once that issue is fixed and we switch to DYNAMIC or whichever the
final solution is, we'll unpin this.
=> Make mariadb:10.5 sticky

lang/en/local_moodlecheck.php, rules/phpdocs_basic.php, tests/fixtures/phpdoc_tags_inline.php, tests/moodlecheck_rules_test.php
Optional descriptions are allowed in inline @link and @see tags. I think it would be good to support this.
For more info, check out:
https://docs.phpdoc.org/3.0/guide/references/phpdoc/inline-tags/
=> Allow support for description when checking inline @link/@see tags

.github/workflows/ci.yml, locallib.php, rules/phpdocs_basic.php, rules/phpdocs_package.php
Since some time ago, GH is warning us that the Ubuntu 18.04 environment is deprecated:
"The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead...."
Hence, we are bumping here, to be able to cerify if everything continues working ok
=> Bump GHA environments to use Ubuntu 22.04 (up from 18.04)

file.php, locallib.php, rules/phpdocs_basic.php, tests/fixtures/phpdoc_method_overrides.php, tests/moodlecheck_rules_test.php
To make this possible, rule functions can now return a severity which will override the rule severity. `local_moodlecheck_functionsdocumented` returns `warning` if the artifact contains an `extends` or `implements` clause. Otherwise, it returns no severity, so the default `error` is used.
The existence of `extends` and `implements` clauses is determined solely by the existence of the keywords between `class` and `{`. I originally wrote some code to extract the superclass and interface names, but settled on this solution for simplicity.
I also changed the `$isphpunitfile` to also match test files in subdirectories. The previous pattern required test files to be directly below a `tests/` dir, which I believed to be a mistake.
Fixes #82
=> #82: Make undocumented methods in subclasses warnings

file.php, tests/fixtures/phpdoc_properties.php, tests/moodlecheck_rules_test.php
This implementation assumes that anything between modifier and property name is part of the property type and skips it before looking for the modifiers and PHPdoc. Judging by [the PHP yacc grammar](https://github.com/php/php-src/blob/c398694e19a7ad8b1e6c2f0fa9b489d405aa0219/Zend/zend_language_parser.y#L933), this should be correct.
Fixes #81
=> #81: Correctly detect PHPdoc on PHP 7.4 typed properties

index.php, locallib.php
Right now it's not possible to reload (F5) the moodlecheck page in order to re-execute the checks automatically.
That's a feature that the sister page @ codechecker has, and it's a facility to progressively got fixing and re-executing the same configured checks.
Basically implies to read all the params and perform a redirect so all the information is in the URL, available for re-execution.
No change in results or cli are expected, just the web/UI moodlecheck page can now be reloaded (in practice), that also implies that it's possible to invoke it from other places via properly escaped URL, for example:
site://local/moodlecheck/?path=mod%2Fforum
Fixes #88
=> Allow the form to reload, for easier re-executions

file.php, rules/phpdocs_basic.php, rules/phpdocs_package.php, tests/fixtures/phpdoc_tags_packagespecified.php, tests/moodlecheck_rules_test.php
Previously, only the class containing a function was retrieved and used in either rule. Now, the containing artifact is also looked up if it is an interface or a trait. Function objects contain a new `owner` property for this. I haven't removed the `class` property yet because I wasn't sure if there's some third-party code that could depend on it.
To include the correct artifact type (`class`, `interface`, or `trait`) in warnings, artifacts additional gain the property `typestring` containing one of those three strings.
Fixes #96
=> #96: Support interfaces and traits in packagespecified and functionsdocumented

rules/coreapis.txt, rules/phpdocs_package.php
Note that soon, we'll replace this by the APIs being bundled with core (see MDL-71096), but this is a switch to be able to compare results before and after, leaving the old docs out from the equation.
Note I've tested results locally and I've got exactly the same results with:
1. The old dev docs page.
2. The new dev docs page (with this PR applied).
3. The copy of the new docs page bundled within local_moodlecheck (with this PR applied).
> string(424) "access, admin, adminpresets, analytics, availability, backup, badges, cache, calendar, check, comment, competency, completion, core, ddl, dml, enrol, event, external, files, form, grade, grading, group, h5p, lock, log, media, message, navigation, oauth2, output, page, payment, plagiarism, portfolio, preference, privacy, question, rating, …
=> Move from old dev docs to new ones to fetch existing APIs

rules/phpdocs_basic.php
The PHP 8.x tokenizer now provides more granular results than the one in previous PHP versions. Specifically about whitespace.
For example, every comment (//) line was previously reported as a list of T_COMMENT tokens (all together). And now it's a list of T_COMMENT + T_WHITESPACE.  So they almost double.
Hence, we are here allowing the code to look for the 1st line not being comments further, from old 30 (that was enough for files with non-standard comments header like config-dist.php) to 90 (3x), to ensure that there are more chances to find that first non-comment line.
Note that CiBoT reports all problems detected not having a line specified, so config-dist.php was being reported always. With this change it will come with a line found... and it won't be reported any more.
=> Look further for first non-comment/white space line

.github/workflows/ci.yml
This is part of the php81 epic:
https://tracker.moodle.org/browse/MDL-73016
It's near completed and passing in CIs, so let's enable the php81
tests for both MOODLE_401_STABLE and master (4.2dev).
=> Add php81 tests

file.php, tests/fixtures/anonymous/anonymous_with_params.php, tests/fixtures/anonymous/extends_with_params.php, tests/fixtures/anonymous/implements_with_params.php, tests/moodlecheck_rules_test.php
We already were supporting anon classes, allowing them not to be documented.
This PR just enables anon classes with params to follow the same path. We'll just skip any (between brackets) parameters in the class declaration and will continue looking for a extends/implements/body like we were doing already.
Note this fixes #91
=> Anon classes with params do not required phpdocs either

renderer.php, tests/coverage.php, tests/fixtures/error_and_warning.php, tests/moodlecheck_rules_test.php
Note that the xml format already includes that severity (error or warning) information.
Covered with unit tests, we also are introducing here a coverage.php file to add some locations that are not considered by default.
We need that information to be able to discern, with other tools, between warning and errors. See for example https://github.com/moodlehq/moodle-plugin-ci/issues/186
Ciao :-)
=> Add severity information to text and html formats

tests/fixtures/phpdoc_properties.php, tests/moodlecheck_rules_test.php
1. Constants have to be documented.
2. The @const tag is forbidden. Constants are documented with @var, if anything.
Note that this does not change anything in moodlecheck, but just covers with tests the detection of undocumented constants and the (incorrect) use of the @const tag.
Note that this is part of https://tracker.moodle.org/browse/MDL-77599
=> Ensure that we have covered with tests some constants phpdoc checks

file.php, tests/fixtures/uses.php, tests/moodlecheck_rules_test.php
`get_functions` and `get_constants` previously interpreted these statements as functions and constants themselves, leading to false positives.
It would have been somewhat simpler to check if the `T_FUNCTION`/`T_CONST` is directly preceded by a `T_USE`, but that doesn't support the "grouped" use statements. (`use { function a, const B };`) Instead, I skip to the next semicolon (or ?> or EOF) when T_USE is encountered.
=> Support "use function" and "use const"

file.php, rules/phpdocs_basic.php, rules/phpdocs_package.php, tests/fixtures/phpdoc_constructor_property_promotion.php, tests/fixtures/phpdoc_method_union_types.php, tests/moodlecheck_rules_test.php
This is a bit of a mixed bag, but the original thing came from adding support for union types.
When writing the testcases I discovered that we did not support:
* union types (that is `string|int|float`)
* mis-ordered params (that is `int|float` in docs, and `float|int` in the type hint)
* nullable types (that is `?string`)
* array types in docs (that is `string[]`)
This series of commits:
* adds tests which cover all of these features
* adds support for union types
* adds support for nullable types
* adds support for array type normalisation
* normalises the order of types and param docs
As part of this change I've tried to improve the token parsing to be clearer too.
=> Union types

file.php, tests/fixtures/phpdoc_tags_general.php
In PHP 7.4 the object type in a parameter or return type were tokenised to individual namespace components. For example:
\core\course
Becomes
\
core
\
course
From PHP 8.0, it is tokenized to \core\course.
This change attempts to normalise these values.
Fixes #116
=> Normalise php 7.4 class namespaces

file.php, rules/phpdocs_basic.php, tests/fixtures/phpdoc_tags_general.php, tests/phpdocs_basic_test.php
When converting tokens from 7.4 format to 8.x format, we need to break on whitespace to get the same result.
=> Split on whitespace when normalising for php 7.4

lang/en/local_moodlecheck.php, rules/phpdocs_basic.php, tests/moodlecheck_rules_test.php, tests/phpdocs_basic_test.php
Remove noemptysecondlines check
Already covered by:
* moodle.Files.BoilerplateComment.NoPHP
* PSR12.Files.FileHeader.HeaderPosition
=> Remove noemptysecondlines check

file.php, tests/fixtures/phpdoc_constructor_property_promotion_readonly.php, tests/moodlecheck_rules_test.php
```php
public function __construct(
public readonly int $foo,
protected readonly int $bar,
) {}
```
The `readonly` keywords were being detected as types.
=> Add support for readonly constructor properties

file.php, lang/en/local_moodlecheck.php, rules/phpdocs_basic.php, tests/moodlecheck_rules_test.php
Replaced by https://github.com/moodlehq/moodle-cs/pull/129
=> Remove constsdocumented

file.php, lang/en/local_moodlecheck.php, rules/phpdocs_basic.php
Replaced by https://github.com/moodlehq/moodle-cs/pull/134
=> Remove phpdocsfistline and functiondescription (#142)

file.php, lang/en/local_moodlecheck.php, rules/phpdocs_basic.php
These checks never worked. The `get_defines()` method built a list of definitions, added them to a `$defines` array, but return `$this->defines` instead.
Furthermore there would be pandamonium if we actually fixed this because we use constants in scripts all over Moodle with the same value, for example:
```
define('CLI_SCRIPT', true);
```
=> Remove all checks for define()

file.php, lang/en/local_moodlecheck.php, rules/phpdocs_basic.php
The last usage of this was removed when we removed the variableshasvar sniff.
=> Remove unused code (variables)
